export { default as Home } from './Home';
export { default as Collections } from './Collections';
export { default as Favorites } from './Favorites';
export { default as Search } from './Search';
export { default as SnippetView } from './SnippetView';
export { default as Login } from './Login';
export { default as Profile } from './Profile';
export { default as CreateSnippet } from './CreateSnippet';
export { default as Settings } from './Settings';
export { About } from './About'; 